image: python:latest

pages:
  stage: deploy
  script:
    - python3 build.py gh-pages-deploy
    - python3 -m pip install -r requirements.txt
  artifacts:
    paths:
      - build
  only:
    - main
